name: test234
favicon: null
layout_spectrum: 0.90723
typography_spectrum: 0.72457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5625
  lightness: 0.6875
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
